from pathlib import Path
import re

import pytest

from shppy.atom import Atoms
from shppy.io.espresso import EspressoParser, EspressoIn

FIXTURE_PATH = Path(__file__).parent / "data" / "espresso" / "ice_mol.xml"
INPUT_FIXTURE_PATH = Path(__file__).parent / "data" / "espresso" / "test.in"
assert FIXTURE_PATH.exists(), "tests/data/espresso/ice_mol.xml fixture is missing"
assert INPUT_FIXTURE_PATH.exists(), "tests/data/espresso/test.in fixture is missing"


@pytest.fixture(scope="module")
def espresso_parser():
    return EspressoParser(FIXTURE_PATH)


def test_parser_loads_metadata(espresso_parser):
    assert espresso_parser.bc
    assert isinstance(espresso_parser.pbc, tuple)
    assert isinstance(espresso_parser.out_energy.etot, float)
    assert isinstance(espresso_parser._hf_unit, bool)


def test_step_atoms_single(espresso_parser):
    atoms = espresso_parser.step_atoms(0)
    assert isinstance(atoms, Atoms)
    assert len(atoms) > 0
    assert tuple(bool(flag) for flag in atoms.pbc) == espresso_parser.pbc


def test_step_atoms_slice(espresso_parser):
    atoms_list = espresso_parser.step_atoms(slice(0, 2))
    assert isinstance(atoms_list, list)
    assert len(atoms_list) == 2
    for atoms in atoms_list:
        assert isinstance(atoms, Atoms)
        assert atoms.cell.array.shape == (3, 3)


def test_espressoin_read_parses_control_keys_and_types():
    obj = EspressoIn.read(INPUT_FIXTURE_PATH)

    assert obj.control["pseudo_dir"] == "./pseudo/"
    assert obj.control["tprnfor"] is True
    assert obj.control["tstress"] is True
    assert obj.control["verbosity"] == "low"
    assert obj.control["lfcp"] is False
    assert obj.control["forc_conv_thr"] == pytest.approx(1e-3)
    assert obj.control["outdir"] == "./out0/"


def test_espressoin_write_roundtrip_format(tmp_path):
    obj = EspressoIn.read(INPUT_FIXTURE_PATH)
    out_path = tmp_path / "qe_generated.in"
    obj.write(out_path)

    text = out_path.read_text(encoding="utf-8")
    lines = text.splitlines()

    assert lines[0] == "# This file is generated by shppy"
    assert lines[1] == "# For detailed parameters, refer to https://www.quantum-espresso.org/Doc/INPUT_PW.html#id32"

    assert "K_POINTS gamma" in text
    assert "K_POINTS {gamma}" not in text
    assert "CELL_PARAMETERS angstrom" in text
    assert "ATOMIC_POSITIONS angstrom" in text

    conv_thr_line = next(line for line in lines if re.search(r"\bconv_thr\b", line))
    assert "1.d-5" in conv_thr_line

    outdir_line = next(line for line in lines if re.search(r"\boutdir\b", line))
    assert "'./out0/'" in outdir_line

    # Ensure constrained and unconstrained ATOMIC_POSITIONS lines both appear.
    assert any(line.strip().endswith("0 0 0") for line in lines if line.strip().startswith(("H ", "C ", "N ", "O ", "Cu ")))
    atom_lines = [line for line in lines if line.startswith("  ") and len(line.split()) >= 4 and line.split()[0] in {"H", "C", "N", "O", "Cu"}]
    assert any(len(line.split()) == 4 for line in atom_lines)
